---
driver_plugin: docker
driver_config:
  require_chef_omnibus: true

platforms:
- name: debian-7
  driver_config:
    image: inokappa/wheezy-7.2-basic

suites:
- name: default
  run_list: ["recipe[td-agent_cookbook]"]
  attributes: {}
